import './globals.css'
import { Unica_One as UnicaOne } from 'next/font/google'

const unicaOne = UnicaOne({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-unica-one',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${unicaOne.variable} h-screen`}>{children}</body>
    </html >
  )
}
